bioquest/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('main.urls')),
    re_path(r'^_nested_admin/', include('nested_admin.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'   


urlpatterns = [
    path('', views.problems, name='index'),
    path('about/', views.problems, name='about'),
    path('problems/', views.problems, name='problems')
]

main/models.py
"""Conventioanal Django ORM models. Domain logic (aka business logic) is not here! It is in `services.py`."""

from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import URLValidator

from polymorphic.models import PolymorphicModel

class BaseModel(models.Model):
    """From this model we inherit most of the models associated with different features."""

    created_at = models.DateTimeField('Created', auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        abstract = True

class BasePolymorphic(PolymorphicModel):
    """From this model we inherit some of the models, which are a qukte abstract."""

    created_at = models.DateTimeField('Created', auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField('Modified', auto_now=True)

    class Meta:
        abstract = True

class Profile(BaseModel):
	user = models.OneToOneField(User, on_delete=models.CASCADE)

class ImageAlbum(BaseModel):
    """To have an ability to add multiple images to models"""

    @property
    def model(self):
        """To get the model, which refers to the ImageAlbum instance (among the models having multple images)"""

        fields =  ImageAlbum._meta.get_fields()
        related_models = [field.name for field in fields if field.get_internal_type() == 'OneToOneField']

        for related_model in related_models:
            if hasattr(self, related_model):
                return getattr(self, related_model)


    def __str__(self):
        if self.model is None:
            return 'Набор изображений'
        return f'Изображения для "{self.model}" ({self.model._meta.verbose_name.title()})'
    
    class Meta:
        verbose_name = 'Набор изображений'
        verbose_name_plural = 'Наборы изображений'
        ordering = ['-id']

class Image(BaseModel):
    """To store images for the models"""

    file = models.ImageField(upload_to='images/')
    album = models.ForeignKey(ImageAlbum, related_name='images', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

    def __str__(self):
        if self.album.model is None:
            return 'Изображение'
        return f'Изображение для "{self.album.model}" ({self.album.model._meta.verbose_name.title()})'


class Section(BaseModel):
    """To sort questions by quite big areas of knowledge. Every question can be in multiple sections."""

    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    class Meta:
        ordering = ['name']
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('section_url', kwargs={'slug': self.slug})

class Topic(BaseModel):
    """To sort questions by particular topics. Every question can have multiple topics."""
    
    parent_section = models.ForeignKey(Section, on_delete=models.CASCADE, null=True, related_name='topics')
    name = models.CharField(max_length=100)
    
    class Meta:
        ordering = ['parent_section', 'name']
        verbose_name = 'Тема'
        verbose_name_plural = 'Темы'
    
    def __str__(self):
        return self.name

class Competition(BaseModel):
    """To sort questions by competition, where they were taken from."""

    name = models.CharField('Олимпиада', max_length=300, default='ВсОШ', null=True)
    link = models.CharField('Ссылка', max_length=300, validators=[URLValidator()])

    class Meta:
        ordering = ['name']
        verbose_name = 'Олимпиада'
        verbose_name_plural = 'Олимпиады'

    def __str__(self):
        return self.name

class BaseQuestion(BasePolymorphic):
    """Abstract model to store different questions: both olympiads and just tests."""

    text = models.TextField('Текст вопроса', null=True)
    max_score = models.FloatField('Балл', null=True, default=0.0)

    images = models.OneToOneField(ImageAlbum, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Иллюстрации к вопросу')

    quauthor = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        related_name='%(class)s',
        verbose_name='Добавил вопрос'
    )

    sections = models.ManyToManyField(
        Section, blank=True,
        related_name='%(class)s', verbose_name=Section._meta.verbose_name_plural.title()
    )
    topics = models.ManyToManyField(
        Topic, blank=True, 
        related_name='%(class)s', verbose_name=Topic._meta.verbose_name_plural.title()
    )

    class Styles(models.TextChoices):
        PART1 = 'P1', ('1 правильный ответ')
        PART2 = 'P2', ('Множественный выбор')
        RELATE = 'REL', ('Вопрос на соответствие')
        STR = 'STR', ('Текстовый ответ')

    style = models.CharField(
        'Тип',
        max_length=4,
        choices=Styles.choices,
        default=Styles.STR,
    )

class Question(BaseQuestion):
    """To store questions from olympiads. Main model with a lot of information.
    Related domain-speccific aspects are in `QuestionExtended`."""
    
    competition = models.ForeignKey(
        Competition, on_delete=models.CASCADE, null=True,
        related_name='questions', verbose_name=Competition._meta.verbose_name.title()
    )

    year = models.IntegerField('Год проведения', null=True)
    stage = models.CharField('Этап', max_length=100, null=True)
    grade = models.IntegerField('Класс', null=True)

    part = models.CharField('Часть', max_length=100, null=True)
    number = models.IntegerField('Номер', null=True)

    class Meta:
        verbose_name = 'Вопрос с олимпиад'
        verbose_name_plural = 'Вопросы с олимпиад'
        ordering = ['-id']

    def __str__(self):
        shortened = str(self.text)[:25] + '...'
        return shortened

class SolvedQuestion(BaseModel):
    """To store information about the questions solved by different users."""

    parent_question = models.ForeignKey(BaseQuestion, on_delete=models.CASCADE, related_name='solved')

class BaseAnswer(BaseModel):
    """To store answers for the questions. It is an abstract class, because there are dufferent types of answers: right and user.
    Right answer has foreign key to polymorphic BaseQuestion, user answer - to SolvedQuestion.
    We need it, because we want to have an ability to add multiple answers for one question (if we have several points in it, for example)."""

    label = models.TextField('Пункт', null=True)
    text = models.TextField('Ответ', null=True)

    class Meta:
        abstract = True
    
class RightAnswer(BaseAnswer):
    """To store answers for the questions.
    We need it, because we want to have an ability to add multiple answers for one question (if we have several points in it, for example)."""
    
    parent_question = models.ForeignKey(BaseQuestion, on_delete=models.CASCADE, null=True, blank=True, related_name='right_answers')

    class Meta:
        ordering = ['parent_question']
        verbose_name = 'Правильный ответ'
        verbose_name_plural = 'Правильные ответы'

class UserAnswer(BaseAnswer):
    """To store answers for the questions.
    We need it, because we want to have an ability to add multiple answers for one question (if we have several points in it, for example)."""

    parent_solved = models.ForeignKey(SolvedQuestion, on_delete=models.CASCADE, null=True, blank=True, related_name='user_answers')

    class Meta:
        ordering = ['parent_solved']
        verbose_name = 'Ответ пользователя'
        verbose_name_plural = 'Ответы пользователей'


class Explanation(BaseModel):
    """To store explanations for the questions."""

    parent_question = models.OneToOneField(BaseQuestion, on_delete=models.CASCADE, null=True, blank=True)

    text = models.TextField('Разбор, комментарии', blank=False)
    images = models.OneToOneField(ImageAlbum, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Иллюстрации к разбору')

    explauthor = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True, blank=True,
        related_name='comments',
        verbose_name='Добавил разбор')

    mark = models.BooleanField('Проверено экспертом', default=False)

    class Meta:
        ordering = ['parent_question']
        verbose_name = 'Разбор'
        verbose_name_plural = 'Разборы'

main/views.py
from django.shortcuts import render

from .models import Question, Section

def about(request):
    pass

def problems(request):

    questions = Question.objects.order_by('-id')
    sections = Section.objects.order_by('name')

    context = {
        'nav': [True, False, False],
        'questions': questions,
        'sections': sections
    }

    return render(request, 'problems.html', context=context)

main/templates/archive/about.html
{% extends 'index.html' %}

{% block title %}
Проект BioQuest
{% endblock %}

{% block content %}
    <div class="col">
    <h1>Проект BioQuest</h1>
    <p>Цель нашего проекта — создание базы вопросов ВсОШ и перечневых олимпиад по биологии, чтобы школьники из любого региона могли решать вопросы, сортируя их по тематике или олимпиаде.
        Каждый зарегистрированный пользователь может добавлять вопросы в базу, однако мы просим вас делать это вдумчиво и аккуратно, проверять ответы по ключам.
        Чтобы вводить всё правильно, ознакомьтесь с <a href="#"> инструкциями</a>.
        Если у вас есть вопросы, предложения или сообщения об ошибках — пишите нам на почту <a href='mailto:timofei.ryko@gmail.com'>timofei.ryko@gmail.com</a>, указав в теме письма "BioQuest".
        Если вы <b>преподаватель биологии</b> и хотите помочь проекту с добавлением разборов и их редактированием, напишите нам на почту, и мы выдадим вам права администратора.</p>
    </div>
{% endblock %}

main/templates/archive/index.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <style>
        /* кнопки тем и разделов */
        a.pad {display:inline-block;border:1px dashed #007bff;margin:2px;padding:2px 6px;border-radius:8px;}
            a.pad:hover {background:#f0ffff;text-decoration:none;}

        /* ограничение для размера картинок для очень широких экранов, внедрено не везде */
        img.img-in-test {max-height:400px;}

        /* кнопки-ярлыки ответов закрытых вопросов (разделы 1 и 2) */
        .ffield {border:1px dashed #007bff;font-size:120%;border-radius:8px;display:inline-block;margin-bottom:6px;}
            .ffield label {padding:5px 15px 8px;cursor:pointer;display:inline-block;}
            .ffield input {display:none;}
        .ffield.ac,.ffield2.ac {background-color:#007bff;color:#fff;}


        /* стили меню разделов и тем в форме загрузки */
        .tags {}
            .tags ul {list-style:none;padding-inline-start:0;}

        .topic {border:1px dashed #007bff;border-radius:8px;padding:3px;margin:3px 0 3px 10px;}
            .topic h3, .topic h2 {font-size:120%;}

        .vis {display:none}


    </style>

    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function(){

            // привязка декорированных кнопок checkbox и radio к их кнопкам-ярлыкам
	    	$("div.ffield").children("input").change(function() {
	    	    $(this).parent().toggleClass("ac").siblings("div.ffield-radio").removeClass("ac");
	    	})

            // функции разделов и тем в форме загрузки
	        var tagsArr = [1, 2, 3, 4, , 9, 5, 6, 10, 11, 7, 8]; //соответствие разделов блокам тем

            $("#tag0 label").each(function(i) {
                $(".topic h3").eq(tagsArr[i]-1).text($(this).text()); // забираем заголовки разделов в блоки тем
            })

            // открытие/сокрытие и обнуление полей input
            $("#tag0 input").each(function(i) {
                $(this).change(function() {
                    $(".topic").eq(tagsArr[i]-1).toggleClass("vis");
                    if (!$(this).prop("checked")) $(".topic").eq(tagsArr[i]-1).find("input").prop( "checked", false );
                })

            });
		});



    </script>

    {% load static %}
    <script src="{% static 'add.js' %}"></script>

</head>
<body>

  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 pb-3 bg-white border-bottom shadow-sm">

        <h5 class="my-0 mr-md-auto font-weight-normal">BioQuest</h5>

        <nav class="my-2 my-md-0 mr-md-3">
          <a class="font-weight-bold text-dark" href="#" >Личный кабинет</a>
          <a class="p-2 text-dark" href="#">Все вопросы</a>
          <a class="p-2 text-dark" href="{% url 'main:about' %}">О проекте</a>
          <a class="p-2 text-dark" href="#">Добавить вопросы</a>
          <a class="p-2 text-dark" href="#">Инструкции</a>
        </nav>

        <form class="form-inline d-flex justify-content-center md-form form-sm mt-0">
            <i class="fas fa-search" aria-hidden="true"></i>
            <input class="form-control form-control-sm ml-3 w-100" type="text" placeholder="Поиск вопросов"
              aria-label="Search" name="search">
        </form>

  </div>

  <div style="margin:10px 0px 10px 0px">
    {% block content %}{% endblock %}
  </div>

</body>
</html>